# Generated by Django 2.0 on 2018-05-28 14:52

from django.db import migrations, models
import django.db.models.deletion
import ourblog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('blog_text', models.TextField()),
                ('blog_image', models.FileField(null=True, upload_to=ourblog.models.upload_blog_image)),
                ('publish_date', models.DateTimeField(verbose_name='Date published')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Profile bio')),
                ('profile_image', models.FileField(upload_to=ourblog.models.profile_image)),
                ('place_from', models.TextField(blank=True, verbose_name='Place from')),
                ('university_name', models.TextField(blank=True, null=True, verbose_name='University from')),
                ('course_name', models.TextField(blank=True, null=True, verbose_name='Course undertaking')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('publish_date', models.DateTimeField(verbose_name='Date published')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ourblog.Blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ourblog.Blogger'),
        ),
    ]
