# Generated by Django 2.0 on 2018-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='course_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Course undertaking'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='place_from',
            field=models.CharField(blank=True, max_length=100, verbose_name='Place from'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='university_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='University from'),
        ),
    ]
