# Generated by Django 2.0 on 2018-05-28 15:52

from django.db import migrations, models
import ourblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0002_auto_20180528_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.FileField(blank=True, null=True, upload_to=ourblog.models.upload_blog_image),
        ),
    ]
