# Generated by Django 2.0 on 2018-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0004_auto_20180530_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='place_from',
            field=models.TextField(blank=True, choices=[('Juja', 'Juja'), ('Nairobi', 'Nairobi'), ('Kahawa', 'Kahawa'), ('Madaraka', 'Madaraka'), ('Athi-River', 'Athi-River'), ('Karen', 'Karen')], max_length=1, verbose_name='Place from'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='university_name',
            field=models.TextField(blank=True, choices=[('JKUAT', 'Jommo Kenyatta University of Agriculture and technology'), ('UON', 'University of Nairobi'), ('KU', 'Kenyatta University'), ('STRATH', 'Strathmore'), ('DAYSTAR', 'Daystat University'), ('CUEA', 'Cooperative University of East Africa')], max_length=1, null=True, verbose_name='University from'),
        ),
    ]
